#ComBlockCommandSearchAndReplace Configuration File

#debug mode active or not (will show additional messages to help troubleshooting)
debug: false

# only check the first X characters of a command for replaceable values;
# 0 checks everything
search-first-chars: 0

# prefix message in chat
message-prefix: '&2[&rVectorCalc&2]'

# primary color of chat messages
primary-color: '&a'

# secondary color of chat messages
secondary-color: '&r'