name: ComBlockCommandSearchAndReplace
main: de.relulu.ComBlockCommandSearchAndReplace.Init
version: ${project.version}
api-version: 1.13
author: ReLuLu
commands:
  blockpos1:
    description: Sets the reference block for the relation calculation.
    usage: Type /bp1 while looking at your desired reference block or use coordinates /bp1 <x y z>.
    aliases: [bpos1, bp1]
  blockpos2:
    description: Sets the target block for the relation calculation.
    usage: Type /bp2 while looking at your desired target block or use coordinates /bp2 <x y z>.
    aliases: [bpos2, bp2]
  blocksnear:
    description: Creates a selection of n blocks around the player
    usage: Type /blocksnear <n> for creating a cuboid selection of n blocks around you.
    aliases: [bnear, bn]
  blockscancel:
    description: cancels any selection
    usage: Type /blockscancel for cancelling your selection.
    aliases: [bcancel, bcc]
  blockcalc:
    description: Calculates the vector from blockpos1 to blockpos2.
    usage: /blockcalc after both blockpos have been set
    aliases: [bcalc, bc]
  blockreplace:
    description: Modifies / replaces the commands inside of a command blocks (basically a search and replace operation).
    usage: /blockreplace * [new command], /blockreplace [Foo] [Bar] ["Foo bar"] ["Bar foo"]
    aliases: [breplace, brep]
    